user:
  host: user_service
  port: 6000

admin:
  host: admin_service
  port: 7000

books:
  host: books_service
  port: 8000

kafka:
  address: kafka:9092
  brokers:
    - kafka:9092
  writers:
    error: error-log
    info: info-log
    warning: warning-log

redis: redis:6379
