port: ":8000"
postgres:
  host: books_postgres
  port: 5432
  user: surya
  password: 123
  dbname: book_store_books
  sslmode: disable
kafka:
  address: kafka:9092
  brokers:
    - kafka:9092
  writers:
    error: error-log
    info: info-log
    warning: warning-log
