# Stage 1 ~ Caching modules
FROM golang:1.23.2-alpine AS modules
WORKDIR /modules
COPY go.* ./
RUN go mod tidy

# Stage 2 ~ Builder
FROM golang:1.23.2-alpine AS builder
COPY --from=modules /go/pkg /go/pkg
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -tags migrate -o /bin/app .

# Stage 3 ~ Final
FROM scratch

EXPOSE 6000
COPY --from=builder /app/config.yml /
COPY --from=builder /bin/app .
CMD [ "./app" ]